version: "3"
services:
  ganache:
    image: schadokar/eth-ganache:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "7545:7545"
  dapp:
    image: schadokar/eth-server:1.0.0
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - ganache

  # react:
  #   image: schadokar/eth-react:1.0.0
  #   build: ./client
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - dapp